# Server Port
server:
  port: 8080
  tomcat:
    additional-tld-skip-patterns: "*.jar"
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:p6spy:oracle:thin:@121.167.219.232:1522:XE  #origin url:jdbc:p6spy:oracle:thin:@192.168.0.99:1522:XE
    username: CWCON
    password: 1234
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
  mapper-locations:
  - /mybatis/mapper/oracle/**/**.xml
  
logging:
  level:
    '[org.springframework.web]': TRACE
    '[org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor]': INFO
    '[com.korbiztech.product.cocs]': INFO
